# Generated by Django 3.0.5 on 2020-04-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Key', models.SlugField(max_length=200, unique=True)),
                ('Writer', models.CharField(max_length=200)),
                ('Updated_On', models.DateTimeField(auto_now=True)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Content', models.TextField()),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'PUBLISH')], default=0)),
            ],
            options={
                'ordering': ['-Created_On'],
            },
        ),
    ]
