# Generated by Django 3.0.5 on 2020-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200414_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='gc_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
