# Generated by Django 3.0.5 on 2020-04-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gc_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gc_register',
        ),
    ]
