# Generated by Django 3.0.5 on 2020-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_post_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
